export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const PLAYER_MOVEMENT_VERTICAL_VELOCITY = 50;
export const PLAYER_BULLET_MAX = 12;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_SPEED = 500;
export const PLAYER_BULLET_LIFESPAN = 3.5;
export const PLAYER_BULLET_SCALE = 0.012;
export const PLAYER_HEALTH = 4;

export const ENEMY_PINK_CHICKEN_HEALTH = 2;
export const ENEMY_PINK_CHICKEN_HORIZONTAL_VELOCITY = 10;
export const ENEMY_PINK_CHICKEN_BULLET_MAX = 6;
export const ENEMY_PINK_CHICKEN_BULLET_INTERVAL = 4000;
export const ENEMY_PINK_CHICKEN_BULLET_SPEED = -280;
export const ENEMY_PINK_CHICKEN_BULLET_LIFESPAN = 3.5;
export const ENEMY_PINK_CHICKEN_BULLET_SCALE = 0.012;
export const ENEMY_PINK_CHICKEN_GROUP_SPAWN_INTERVAL = 5000;
export const ENEMY_PINK_CHICKEN_GROUP_SPAWN_START = 1000;

export const ENEMY_GREEN_CHICKEN_HEALTH = 1;
export const ENEMY_GREEN_CHICKEN_HORIZONTAL_VELOCITY = 11;
export const ENEMY_GREEN_CHICKEN_VERTICAL_VELOCITY = 8;
export const ENEMY_GREEN_CHICKEN_WAVE_FACTOR = 0.002;
export const ENEMY_GREEN_CHICKEN_GROUP_SPAWN_INTERVAL = 5000;
export const ENEMY_GREEN_CHICKEN_GROUP_SPAWN_START = 1000;

export const ENEMY_EVIL_CHICKEN_HEALTH = 3;
export const ENEMY_EVIL_CHICKEN_HORIZONTAL_VELOCITY = 12;
export const ENEMY_EVIL_CHICKEN_GROUP_SPAWN_INTERVAL = 2000;
export const ENEMY_EVIL_CHICKEN_GROUP_SPAWN_START = 0;

export const ENEMY_EVIL_CHICKEN_BOSS_HEALTH = 30;
export const ENEMY_EVIL_CHICKEN_BOSS_VERTICAL_VELOCITY = 8;
export const ENEMY_EVIL_CHICKEN_BOSS_VERTICAL_WAVE_FACTOR = 0.001;
export const ENEMY_EVIL_CHICKEN_BOSS_GROUP_SPAWN_INTERVAL = 3000;
export const ENEMY_EVIL_CHICKEN_BOSS_GROUP_SPAWN_START = 15000;

export const ENEMY_BABY_EVIL_CHICKEN_HEALTH = 1;
export const ENEMY_BABY_EVIL_CHICKEN_HORIZONTAL_VELOCITY = 9;

export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;

export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;

export const DEFAULT_SPRITE_SCALE = 0.020;